name: Component tests
on:
  push:
    branches:
      - "*"
      - "!master"
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          component: true
